from __future__ import annotations

import json
import os
import subprocess  # nosec B404
import tarfile
import tempfile
from datetime import UTC, datetime, timedelta
from pathlib import Path

from common import parse_postgres_url, require_env, run, safe_filename, sha256_file

RELEASE_TAG = "database-backups"


def ensure_release(repository: str, token: str) -> None:
    env = os.environ.copy()
    env["GH_TOKEN"] = token
    result = subprocess.run(  # nosec B603 B607
        ["gh", "release", "view", RELEASE_TAG, "--repo", repository],
        env=env,
        capture_output=True,
    )
    if result.returncode == 0:
        return
    target = os.environ.get("GITHUB_SHA", "").strip() or os.environ.get("GITHUB_REF_NAME", "main")
    run(
        [
            "gh",
            "release",
            "create",
            RELEASE_TAG,
            "--repo",
            repository,
            "--target",
            target,
            "--title",
            "CampusPass Encrypted Database Backups",
            "--notes",
            "Rolling encrypted PostgreSQL backups generated by GitHub Actions.",
        ],
        env=env,
    )


def upload_assets(repository: str, token: str, *paths: Path) -> None:
    env = os.environ.copy()
    env["GH_TOKEN"] = token
    run(
        [
            "gh",
            "release",
            "upload",
            RELEASE_TAG,
            *[str(path) for path in paths],
            "--clobber",
            "--repo",
            repository,
        ],
        env=env,
    )


def remove_expired_assets(repository: str, token: str, retention_days: int) -> int:
    env = os.environ.copy()
    env["GH_TOKEN"] = token
    response = run(
        [
            "gh",
            "api",
            f"repos/{repository}/releases/tags/{RELEASE_TAG}",
        ],
        env=env,
    )
    release = json.loads(response.stdout.decode())
    assets = sorted(
        release.get("assets", []),
        key=lambda item: item.get("created_at", ""),
        reverse=True,
    )
    cutoff = datetime.now(UTC) - timedelta(days=retention_days)
    deleted = 0
    for index, asset in enumerate(assets):
        # Always retain at least three newest assets, including checksum companions.
        if index < 6:
            continue
        created_at = datetime.fromisoformat(asset["created_at"].replace("Z", "+00:00"))
        if created_at >= cutoff:
            continue
        run(
            [
                "gh",
                "api",
                "--method",
                "DELETE",
                f"repos/{repository}/releases/assets/{asset['id']}",
            ],
            env=env,
        )
        deleted += 1
    return deleted


def main() -> None:
    database_url = require_env("BACKUP_DATABASE_URL")
    encryption_key = require_env("BACKUP_ENCRYPTION_KEY")
    repository = require_env("GITHUB_REPOSITORY")
    token = require_env("GITHUB_TOKEN")
    retention_days = max(3, min(365, int(os.environ.get("BACKUP_RETENTION_DAYS", "14"))))
    connection = parse_postgres_url(database_url)
    timestamp = datetime.now(UTC).strftime("%Y%m%dT%H%M%SZ")
    prefix = safe_filename(f"campuspass-{connection.database}-{timestamp}")

    with tempfile.TemporaryDirectory(prefix="campuspass-backup-") as temporary:
        workdir = Path(temporary)
        dump_path = workdir / "database.dump"
        manifest_path = workdir / "manifest.json"
        archive_path = workdir / f"{prefix}.tar.gz"
        encrypted_path = Path.cwd() / f"{prefix}.tar.gz.gpg"
        checksum_path = Path.cwd() / f"{prefix}.sha256"

        pg_env = connection.pg_environment()
        run(
            [
                "pg_dump",
                "--format=custom",
                "--compress=9",
                "--no-owner",
                "--no-acl",
                "--file",
                str(dump_path),
            ],
            env=pg_env,
        )
        manifest = {
            "created_at": datetime.now(UTC).isoformat(),
            "database_host": connection.host,
            "database_port": connection.port,
            "database_name": connection.database,
            "repository": repository,
            "commit": os.environ.get("GITHUB_SHA", ""),
            "dump_sha256": sha256_file(dump_path),
            "format": "pg_dump custom",
            "encrypted": True,
        }
        manifest_path.write_text(
            json.dumps(manifest, ensure_ascii=False, indent=2), encoding="utf-8"
        )
        with tarfile.open(archive_path, "w:gz") as archive:
            archive.add(dump_path, arcname="database.dump")
            archive.add(manifest_path, arcname="manifest.json")
        run(
            [
                "gpg",
                "--batch",
                "--yes",
                "--pinentry-mode",
                "loopback",
                "--passphrase-fd",
                "0",
                "--symmetric",
                "--cipher-algo",
                "AES256",
                "--output",
                str(encrypted_path),
                str(archive_path),
            ],
            input_bytes=encryption_key.encode(),
        )
        checksum = sha256_file(encrypted_path)
        checksum_path.write_text(f"{checksum}  {encrypted_path.name}\n", encoding="utf-8")

        ensure_release(repository, token)
        upload_assets(repository, token, encrypted_path, checksum_path)
        deleted = remove_expired_assets(repository, token, retention_days)
        print(
            json.dumps(
                {
                    "ok": True,
                    "asset": encrypted_path.name,
                    "checksum": checksum,
                    "retention_days": retention_days,
                    "deleted_old_assets": deleted,
                },
                ensure_ascii=False,
            )
        )
        encrypted_path.unlink(missing_ok=True)
        checksum_path.unlink(missing_ok=True)


if __name__ == "__main__":
    main()
